# Generated by Django 4.2.1 on 2023-06-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255, null=True)),
                ('bookid', models.CharField(max_length=255, null=True)),
                ('bookstatus', models.CharField(max_length=255, null=True)),
                ('bookrating', models.CharField(max_length=255, null=True)),
                ('p_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile')),
            ],
        ),
    ]
