# Generated by Django 4.2.1 on 2023-06-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('onlinebooksys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='p_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile'),
        ),
    ]
