# Generated by Django 4.2.1 on 2023-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooksys', '0002_alter_bookmodel_p_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='bookgenre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='bookoverallrating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='bookvote',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
